// Gate definitions for the twelve keys of one octave (C4–B4).
// White keys carry the "classic" gate set; black keys carry rotations
// and the second entangling pair.

export const PIANO_KEYS = [
  {
    id: 'C',
    type: 'white',
    whiteIndex: 0,
    note: 'C4',
    frequency: 261.63,
    gate: 'H',
    symbol: 'H',
    fullName: 'Hadamard',
    description: 'Creates an equal superposition of |0⟩ and |1⟩.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'D',
    type: 'white',
    whiteIndex: 1,
    note: 'D4',
    frequency: 293.66,
    gate: 'X',
    symbol: 'X',
    fullName: 'Pauli-X',
    description: 'Flips the qubit — the quantum NOT gate.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'E',
    type: 'white',
    whiteIndex: 2,
    note: 'E4',
    frequency: 329.63,
    gate: 'Y',
    symbol: 'Y',
    fullName: 'Pauli-Y',
    description: 'Flips bit and phase together — a rotation about Y.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'F',
    type: 'white',
    whiteIndex: 3,
    note: 'F4',
    frequency: 349.23,
    gate: 'Z',
    symbol: 'Z',
    fullName: 'Pauli-Z',
    description: 'Flips the phase of |1⟩, leaves |0⟩ untouched.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'G',
    type: 'white',
    whiteIndex: 4,
    note: 'G4',
    frequency: 392.0,
    gate: 'S',
    symbol: 'S',
    fullName: 'S Gate (Phase)',
    description: 'A quarter-turn phase rotation — the square root of Z.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'A',
    type: 'white',
    whiteIndex: 5,
    note: 'A4',
    frequency: 440.0,
    gate: 'T',
    symbol: 'T',
    fullName: 'T Gate',
    description: 'An eighth-turn phase rotation — the square root of S.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'B',
    type: 'white',
    whiteIndex: 6,
    note: 'B4',
    frequency: 493.88,
    gate: 'CNOT',
    symbol: 'CNOT',
    fullName: 'Controlled-NOT',
    description: 'Entangles two qubits: flips the target when the control is |1⟩.',
    qubits: [0, 1],
    visual: 'cnot',
    controlQubit: 0,
    targetQubit: 1,
  },
  {
    id: 'Csharp',
    type: 'black',
    whiteIndex: 0,
    note: 'C#4',
    frequency: 277.18,
    gate: 'Rx',
    symbol: 'Rx',
    angleLabel: 'π/4',
    fullName: 'Rotation-X (π/4)',
    description: 'Rotates the qubit π/4 radians about the X-axis.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'Dsharp',
    type: 'black',
    whiteIndex: 1,
    note: 'D#4',
    frequency: 311.13,
    gate: 'Ry',
    symbol: 'Ry',
    angleLabel: 'π/4',
    fullName: 'Rotation-Y (π/4)',
    description: 'Rotates the qubit π/4 radians about the Y-axis.',
    qubits: [0],
    visual: 'box',
  },
  {
    id: 'Fsharp',
    type: 'black',
    whiteIndex: 3,
    note: 'F#4',
    frequency: 369.99,
    gate: 'Rz',
    symbol: 'Rz',
    angleLabel: 'π/4',
    fullName: 'Rotation-Z (π/4)',
    description: 'Rotates the qubit π/4 radians about the Z-axis.',
    qubits: [1],
    visual: 'box',
  },
  {
    id: 'Gsharp',
    type: 'black',
    whiteIndex: 4,
    note: 'G#4',
    frequency: 415.3,
    gate: 'CZ',
    symbol: 'CZ',
    fullName: 'Controlled-Z',
    description: 'Entangles two qubits with a conditional phase flip.',
    qubits: [0, 1],
    visual: 'cz',
  },
  {
    id: 'Asharp',
    type: 'black',
    whiteIndex: 5,
    note: 'A#4',
    frequency: 466.16,
    gate: 'SWAP',
    symbol: 'SWAP',
    fullName: 'SWAP',
    description: 'Exchanges the quantum states of two qubits.',
    qubits: [0, 1],
    visual: 'swap',
  },
];

export const WHITE_KEYS = PIANO_KEYS.filter((k) => k.type === 'white');
export const BLACK_KEYS = PIANO_KEYS.filter((k) => k.type === 'black');

export const GATES_BY_ID = Object.fromEntries(PIANO_KEYS.map((k) => [k.id, k]));

// piano key id -> default keyboard character
export const DEFAULT_KEY_MAP = {
  C: 'a',
  D: 's',
  E: 'd',
  F: 'f',
  G: 'g',
  A: 'h',
  B: 'j',
  Csharp: 'w',
  Dsharp: 'e',
  Fsharp: 't',
  Gsharp: 'y',
  Asharp: 'u',
};
